# Generated by Django 4.1.2 on 2022-10-19 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_alter_artiste_age_alter_song_date_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
